/*
 * FreeListeTest.java
 *
 * Created on 14 mai 2003, 10:34
 */

package srcastra.test;

/**
 *
 * @author  Thomas
 */
public class FreeListeTest extends javax.swing.JFrame {
    
    /** Creates new form FreeListeTest */
     ServeurConnect kiss;
    public FreeListeTest() {
        initComponents();
        kiss=new ServeurConnect();
        kiss.connectServeur();
        initListe();
    }
    public void initListe(){
       liste1.setServeur(kiss.serveur2);
       liste1.setLogin(kiss.tmpgestion2);
       liste1.setModel(new  srcastra.astra.gui.components.combobox.liste.DestinationtListeTableModel(kiss.serveur2,kiss.tmpgestion2,true));
       liste1.init2();     
       liste1.setFreeModeAllow(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        liste1 = new srcastra.astra.gui.components.combobox.liste.Liste();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        liste1.setIsLastComponent(true);
        getContentPane().add(liste1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(400, 300));
        setLocation((screenSize.width-400)/2,(screenSize.height-300)/2);
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new  srcastra.astra.gui.components.combobox.liste.ManageFreeListe().setValue(cleunik,freeLibelle,liste1);        // Add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           freeLibelle=liste1.getFreetexte();
           cleunik=liste1.getCleUnik();
           System.out.println("Liste text "+freeLibelle+"   cle "+cleunik);// Add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new FreeListeTest().show();
    }
    
String freeLibelle;
int cleunik;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private srcastra.astra.gui.components.combobox.liste.Liste liste1;
    // End of variables declaration//GEN-END:variables
    
}
