/*
 * About.java
 *
 * Created on 30 juin 2006, 15:55
 */

package srcastra.astra.gui;

import java.awt.*;

/**
 * @author vincent
 */
public class About extends java.awt.Dialog {

    /**
     * Creates new form About
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(372, 345);

        this.setLocation(getCenterPosition());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/1.GIF")));
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 350);

        pack();
    }//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About(new java.awt.Frame(), true).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;

    // End of variables declaration//GEN-END:variables
    private Point getCenterPosition() {


        Dimension dimProg = this.getSize();


        Dimension dimScreen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();


        int Xp = (dimScreen.width - dimProg.width) / 2;


        int Yp = (dimScreen.height - dimProg.height) / 2;


        return new Point(Xp, Yp);


    }
}
