/*





 * ADateDemo.java





 *





 * Created on 1 octobre 2002, 11:45





 */


package srcastra.astra.gui.components.date.aDate;


/**
 * @author Sébastien
 */


public class ADateDemo extends javax.swing.JFrame {


    /**
     * Creates new form ADateDemo
     */


    public ADateDemo() {


        initComponents();


    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * initialize the form.
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * always regenerated by the Form Editor.
     */


    private void initComponents() {//GEN-BEGIN:initComponents


        aDate1 = new srcastra.astra.gui.components.date.aDate.ADate();


        aTextField1 = new srcastra.astra.gui.components.textFields.ATextField();


        aDate21 = new srcastra.astra.gui.components.date.aDate.ADate2();


        getContentPane().setLayout(new java.awt.FlowLayout());


        addWindowListener(new java.awt.event.WindowAdapter() {


            public void windowClosing(java.awt.event.WindowEvent evt) {


                exitForm(evt);


            }


        });


        aDate1.setGrp_Comp_nextComponent(aTextField1);


        getContentPane().add(aDate1);


        getContentPane().add(aTextField1);


        getContentPane().add(aDate21);


        pack();


    }//GEN-END:initComponents


    /**
     * Exit the Application
     */


    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm


        System.exit(0);


    }//GEN-LAST:event_exitForm


    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {


        new ADateDemo().show();


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables


    private srcastra.astra.gui.components.date.aDate.ADate2 aDate21;


    private srcastra.astra.gui.components.date.aDate.ADate aDate1;


    private srcastra.astra.gui.components.textFields.ATextField aTextField1;

    // End of variables declaration//GEN-END:variables


}





