/*





 * test.java





 *





 * Created on 29 juillet 2002, 15:38





 */


package srcastra.astra.gui.components.textFields;


/**
 * @author Sébastien
 */


public class test extends javax.swing.JFrame {


    /**
     * Creates new form test
     */


    public test() {


        initComponents();


        setDocument();


    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * initialize the form.
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * always regenerated by the Form Editor.
     */


    private void initComponents() {//GEN-BEGIN:initComponents


        aTextField1 = new srcastra.astra.gui.components.textFields.ATextField();


        aTextField2 = new srcastra.astra.gui.components.textFields.ATextField();


        aTextField3 = new srcastra.astra.gui.components.textFields.ATextField();


        aTextField4 = new srcastra.astra.gui.components.textFields.ATextField();


        aTextField5 = new srcastra.astra.gui.components.textFields.ATextField();


        aTextField6 = new srcastra.astra.gui.components.textFields.ATextField();


        getContentPane().setLayout(new java.awt.FlowLayout());


        addWindowListener(new java.awt.event.WindowAdapter() {


            public void windowClosing(java.awt.event.WindowEvent evt) {


                exitForm(evt);


            }


        });


        aTextField1.setGrp_Comp_nextComponent(aTextField2);


        aTextField1.setWarningIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/warning.gif")));


        aTextField1.setWorkingIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/working.gif")));


        getContentPane().add(aTextField1);


        aTextField2.setEnabled(false);


        aTextField2.setGrp_Comp_nextComponent(aTextField3);


        aTextField2.setGrp_Comp_previousComponent(aTextField1);


        aTextField2.setWarningIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/warning.gif")));


        aTextField2.setWorkingIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/working.gif")));


        getContentPane().add(aTextField2);


        aTextField3.setEnabled(false);


        aTextField3.setGrp_Comp_nextComponent(aTextField4);


        aTextField3.setGrp_Comp_previousComponent(aTextField2);


        aTextField3.setWarningIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/warning.gif")));


        aTextField3.setWorkingIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/working.gif")));


        getContentPane().add(aTextField3);


        aTextField4.setEnabled(false);


        aTextField4.setGrp_Comp_nextComponent(aTextField5);


        aTextField4.setGrp_Comp_previousComponent(aTextField3);


        aTextField4.setWarningIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/warning.gif")));


        aTextField4.setWorkingIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/working.gif")));


        getContentPane().add(aTextField4);


        aTextField5.setEnabled(false);


        aTextField5.setGrp_Comp_nextComponent(aTextField6);


        aTextField5.setGrp_Comp_previousComponent(aTextField4);


        aTextField5.setWarningIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/warning.gif")));


        aTextField5.setWorkingIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/working.gif")));


        getContentPane().add(aTextField5);


        aTextField6.setEnabled(false);


        aTextField6.setGrp_Comp_previousComponent(aTextField5);


        aTextField6.setWarningIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/warning.gif")));


        aTextField6.setWorkingIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/aTextfield/working.gif")));


        getContentPane().add(aTextField6);


        pack();


        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();


        setSize(new java.awt.Dimension(400, 300));


        setLocation((screenSize.width - 400) / 2, (screenSize.height - 300) / 2);


    }//GEN-END:initComponents


    private void setDocument() {

//        aTextField1.setDocument(new srcastra.astra.gui.sys.formVerification.DecimalMask2(1, 5, new java.util.Locale("fr", "")));

        //    aTextField2.setDocument(new srcastra.astra.gui.sys.formVerification.IntegerMask(1, 6, new java.util.Locale("fr", "")));

        //  aTextField3.setDocument(new srcastra.astra.gui.sys.formVerification.DecimalMask(2, 2, new java.util.Locale("fr", "")));

        //aTextField4.setDocument(new srcastra.astra.gui.sys.formVerification.StringMask(3, 8, new java.util.Locale("fr", ""), srcastra.astra.gui.sys.formVerification.DefaultMask.ALL_LETTRE_IN_UPPERCASE));


    }


    /**
     * Exit the Application
     */


    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm


        System.exit(0);


    }//GEN-LAST:event_exitForm


    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {


        new test().show();


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables


    private srcastra.astra.gui.components.textFields.ATextField aTextField6;


    private srcastra.astra.gui.components.textFields.ATextField aTextField5;


    private srcastra.astra.gui.components.textFields.ATextField aTextField4;


    private srcastra.astra.gui.components.textFields.ATextField aTextField3;


    private srcastra.astra.gui.components.textFields.ATextField aTextField2;


    private srcastra.astra.gui.components.textFields.ATextField aTextField1;

    // End of variables declaration//GEN-END:variables


}





