/*
 * ParamFrame.java
 *
 * Created on 14 juin 2004, 15:23
 */

package srcastra.astra.gui.modules.param;
import srcastra.astra.sys.rmi.astrainterface;
import srcastra.astra.sys.classetransfert.Loginusers_T;
/**
 *
 * @author  Administrateur
 */
public class ParamFrame extends javax.swing.JDialog {
    
    /** Creates new form ParamFrame */
    Param panel;
    astrainterface serveur;
    Loginusers_T user;
    public ParamFrame(java.awt.Frame parent, boolean modal,astrainterface serveur,Loginusers_T user) {
        super(parent, modal);
        initComponents();
        panel=new Param(serveur,user);
        getContentPane().add(panel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PARAM");
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-500)/2, (screenSize.height-500)/2, 500, 500);
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       // new ParamFrame(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
