/*




 * ProduitAvion.java




 *




 * Created on 8 januari 2003, 9:44




 */


package srcastra.astra.gui.modules.dossier.productSpecification.gestionnairepaneaux;


/**
 * @author Thomas
 */


public class ProduitAvion extends javax.swing.JPanel {


    /**
     * Creates new form ProduitAvion
     */


    public ProduitAvion() {


        initComponents();


    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * initialize the form.
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * <p/>
     * <p/>
     * <p/>
     * always regenerated by the Form Editor.
     */


    private void initComponents() {//GEN-BEGIN:initComponents


        setLayout(new java.awt.BorderLayout());


    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables

    // End of variables declaration//GEN-END:variables


}




