/*
 * SignaletiqueOtherLanguage.java
 *
 * Created on 3 mai 2002, 14:42
 */
package srcastra.astra.gui.modules.signalitique;
import srcastra.astra.sys.rmi.astrainterface;
import srcastra.astra.sys.classetransfert.signaletique.*;
import srcastra.astra.sys.classetransfert.*;
import srcastra.astra.gui.components.actions.actionToolBar.ActionToolBar;
import srcastra.astra.gui.modules.MainScreenModule;
/**
 *
 * @author  Sébastien
 */
public class SignaletiqueOtherLanguage extends javax.swing.JPanel implements java.awt.event.FocusListener {
    /** Creates new form SignaletiqueOtherLanguage */
    public SignaletiqueOtherLanguage(srcastra.astra.sys.rmi.astrainterface serveur, srcastra.astra.sys.classetransfert.Loginusers_T currentUser, ActionToolBar actionToolBar, MainScreenModule parent, int signaletiqueType) {
        initComponents();
        grp_List_LanguageList.setSelectionBackground(new java.awt.Color(221,221,255));
        grp_List_LanguageList.updateUI();
        initComponents2(serveur, currentUser, actionToolBar, parent, signaletiqueType);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        grp_Pan_StatusPan = new javax.swing.JPanel();
        grp_Pan_MainPan = new javax.swing.JPanel();
        grp_Pan_MainContentPan = new javax.swing.JPanel();
        grp_List_LanguageList = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        grp_Pan_SignaletiquePan = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        grp_Pan_ProgressPan = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        grp_Pan_StatusPan.setBackground(java.awt.Color.white);
        grp_Pan_StatusPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        add(grp_Pan_StatusPan, java.awt.BorderLayout.NORTH);

        grp_Pan_MainPan.setLayout(new java.awt.BorderLayout());

        grp_Pan_MainPan.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        grp_Pan_MainContentPan.setLayout(new java.awt.BorderLayout());

        grp_Pan_MainContentPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        grp_List_LanguageList.setPreferredSize(new java.awt.Dimension(150, 0));
        grp_Pan_MainContentPan.add(grp_List_LanguageList, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel6.add(grp_Pan_SignaletiquePan, java.awt.BorderLayout.CENTER);

        grp_Pan_MainContentPan.add(jPanel6, java.awt.BorderLayout.CENTER);

        grp_Pan_MainPan.add(grp_Pan_MainContentPan, java.awt.BorderLayout.CENTER);

        grp_Pan_MainPan.add(jPanel10, java.awt.BorderLayout.NORTH);

        grp_Pan_MainPan.add(grp_Pan_ProgressPan, java.awt.BorderLayout.SOUTH);

        grp_Pan_MainPan.add(jPanel12, java.awt.BorderLayout.WEST);

        grp_Pan_MainPan.add(jPanel13, java.awt.BorderLayout.EAST);

        add(grp_Pan_MainPan, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    private void initComponents2(srcastra.astra.sys.rmi.astrainterface serveur, srcastra.astra.sys.classetransfert.Loginusers_T currentUser, ActionToolBar actionToolBar, MainScreenModule parent, int signaletiqueType) {
        this.serveur=serveur;
         monListener=new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                grp_List_LanguageListValueChanged(e);
            } 
        };    
         try{
         langList=this.serveur.renvLangueSystem(currentUser.getUrcleunik(),0,0);
         setAvaibleLanguage(langList,currentUser.getUrlmcleunik());         
        }catch(java.rmi.RemoteException e)
        {
            System.out.println("erreur dans renvlanguesystem dans signaletiqueotherlangage"+e.getMessage());
        }   
        switch (signaletiqueType) {
            case astrainterface.COMBO_CODE_POST :
                SignaletiqueCodePostaux cp = new SignaletiqueCodePostaux(serveur, currentUser, actionToolBar, parent, this);
                interfaceSign=cp;                
                this.grp_Pan_SignaletiquePan.add(cp);
                break;
            case astrainterface.COMBO_DEVISE :
                SignaletiqueDeviseB cp3=new SignaletiqueDeviseB(serveur, currentUser, actionToolBar, parent,this);
                interfaceSign=cp3;        
                this.grp_Pan_SignaletiquePan.add(cp3);
                break;
            case astrainterface.COMBO_LANGUE :
                SignaletiqueLangueB cp4=new SignaletiqueLangueB(serveur, currentUser, actionToolBar, parent, this);
                interfaceSign=cp4;
                this.grp_Pan_SignaletiquePan.add(cp4);
                break;   
            case astrainterface.COMBO_PAYS :
                SignaletiquePaysB cp2=new SignaletiquePaysB(serveur, currentUser, actionToolBar, parent, this);
                interfaceSign=cp2;                
                this.grp_Pan_SignaletiquePan.add(cp2);
                break;
            case astrainterface.COMBO_TVA_TYPE:
                SignaletiqueTypeTvaB cp5=new SignaletiqueTypeTvaB(serveur, currentUser, actionToolBar, parent, this);
                interfaceSign=cp5;                
                this.grp_Pan_SignaletiquePan.add(cp5);
                break;
             case astrainterface.COMBO_TRANSPORT:
                SignaletiqueTransportB cp6=new SignaletiqueTransportB(serveur, currentUser, actionToolBar, parent, this,parent.getNestedSignaletique());
                interfaceSign=cp6;                
                this.grp_Pan_SignaletiquePan.add(cp6);
                break;
             case astrainterface.COMBO_LOGEMENT:
                 SignaletiqueLogement cp7 = new SignaletiqueLogement(serveur, currentUser, actionToolBar, parent, this,parent.getNestedSignaletique());
                 interfaceSign = cp7;
                 this.grp_Pan_SignaletiquePan.add(cp7);
                 break;
             case astrainterface.COMBO_TITREPERSONNES:
                 SignaletiqueTitrePersonne cp8 = new SignaletiqueTitrePersonne(serveur, currentUser, actionToolBar, parent, this);
                 interfaceSign = cp8;
                 this.grp_Pan_SignaletiquePan.add(cp8);
                 break;
            case astrainterface.COMBO_DESTINATION:
                 SignaletiqueDestination cp9 = new SignaletiqueDestination(serveur, currentUser, actionToolBar, parent, this,parent.getNestedSignaletique());
                 interfaceSign = cp9;
                 this.grp_Pan_SignaletiquePan.add(cp9);
                 break;
             case astrainterface.COMBO_COMPAGNIE:
                 SignaletiqueCompagnie cp10 = new SignaletiqueCompagnie(serveur, currentUser, actionToolBar, parent, this,parent.getNestedSignaletique());
                 interfaceSign = cp10;
                 this.grp_Pan_SignaletiquePan.add(cp10);
                 break;
             case astrainterface.COMBO_EMBARQDEBARQ:
                 SignaletiqueEmbarqDebarq cp11 = new SignaletiqueEmbarqDebarq(serveur, currentUser, actionToolBar, parent, this,parent.getNestedSignaletique());
                 interfaceSign = cp11;
                 this.grp_Pan_SignaletiquePan.add(cp11);
                 break;
                //interfaceSign=new SignaletiquePays(serveur, currentUser, actionToolBar, parent,this);
                //this.grp_Pan_SignaletiquePan.add(interfaceSign);
        }  
    
         //grp_List_LanguageList.addListSelectionListener(monListener); 
       
    }
    
   
    public void setAvaibleLanguage(java.util.ArrayList donnee,int lmcleunik) {
        // vérification de l'intégritéé des données
        //grp_List_LanguageList.removeListSelectionListener(monListener);
        if (donnee != null) {
            this.langList = donnee;
        }
        else {
            this.langList = new java.util.ArrayList();
        }
        // chargement de l'array au sein de la JList
        listModel = new javax.swing.DefaultListModel();
        for (int i=0; i < donnee.size(); i++) {
            Object[] obj = (Object[]) donnee.get(i);
            listModel.addElement((String) obj[1]);
        }
        grp_List_LanguageList.setModel(listModel);
        grp_List_LanguageList.setCellRenderer(new PictureCellRenderer());
        grp_List_LanguageList.setSelectedIndex(lmcleunik-1);
        setLmcleunik(lmcleunik);
        defaultLangue=lmcleunik;
        grp_List_LanguageList.addListSelectionListener(monListener);
        grp_List_LanguageList.addFocusListener(this);
    }
    private void grp_List_LanguageListValueChanged(javax.swing.event.ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            int cr = grp_List_LanguageList.getSelectedIndex();
            System.out.println("valeur de cr"+cr);
            if (cr < langList.size()) {
                //Object[] obj = (Object[]) langList.get(cr);
                 //System.out.println(obj[2].toString());    
                 //grp_Pan_SignaletiquePan.
               interfaceSign.updateAllFields(cr+1);
               setLmcleunik(cr+1);
            }
        }
    }
    private int setDefaultLangue()
    {   int tmp=(getDefaultLangue()-1);
        grp_List_LanguageList.setSelectedIndex(tmp); 
        return tmp;   
    }
    private String[] getTraduction(Object[] object) {
        String[] retString = null;
        if (object.length > 2) {
            int size = object.length - 2;
            retString = new String[size];
            size = 0;
            for (int i=1; i < object.length; i++) {
                retString[size] = (String) object[i];
                size++;
            }
        }
        return retString;
    }
    public void setEnabled_grp_List_LanguageList(boolean sw)
    {
        grp_List_LanguageList.setEnabled(sw);     
    }
    public class PictureCellRenderer extends javax.swing.DefaultListCellRenderer {
        public java.awt.Component getListCellRendererComponent (javax.swing.JList list, 
                                                                Object value,
                                                                int index,
                                                                boolean isSelected,
                                                                boolean cellHasFocus ) {
                                                                    
              java.awt.Component retValue = super.getListCellRendererComponent (list, value, index, isSelected, cellHasFocus );
              Object[] obj = (Object[]) langList.get(index);
              String rec = java.util.ResourceBundle.getBundle("srcastra/astra/gui/sys/properties/SystemLanguageFlags").getString(obj[0].toString());
              setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcastra/astra/gui/img/flags/" + rec)));
              return retValue;
        }
                                                                
    }
    public int setMode(int mode)
    {
     this.mode=mode;
     //if(mode==interfaceSign.INSERT_MODE)
       //  setEnabled_grp_List_LanguageList(false);
     //else if(mode==interfaceSign.INSERT_DISPLAY_MODE)
       //  setE
     return mode;
    }
    
    /** Getter for property lmcleunik.
     * @return Value of property lmcleunik.
     */
    public int getLmcleunik() {
        return lmcleunik;
    }
    
    /** Setter for property lmcleunik.
     * @param lmcleunik New value of property lmcleunik.
     */
    public void setLmcleunik(int lmcleunik) {
        this.lmcleunik = lmcleunik;
    }
    
    /** Getter for property defaultLangue.
     * @return Value of property defaultLangue.
     */
    public int getDefaultLangue() {
        return defaultLangue;
    }    
    
    public void focusLost(java.awt.event.FocusEvent focusEvent) {
      grp_List_LanguageList.setSelectionBackground(new java.awt.Color(221,221,255));
       interfaceSign.setFocusToCombo(true);
    }
    
    public void focusGained(java.awt.event.FocusEvent focusEvent) {
      grp_List_LanguageList.setSelectionBackground(new java.awt.Color(0,0,153));
      interfaceSign.setFocusToCombo(false);
    }
    void setFocusToCombo(boolean x)
    {
    }
    
    /** Setter for property defaultLangue.
     * @param defaultLangue New value of property defaultLangue.
     */
    private java.util.ArrayList langList;
    private javax.swing.DefaultListModel listModel;
    javax.swing.event.ListSelectionListener monListener;
    private int mode;
    private int lmcleunik;
    private int defaultLangue;
    private astrainterface serveur;
    private Signaletique interfaceSign;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList grp_List_LanguageList;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel grp_Pan_MainContentPan;
    private javax.swing.JPanel grp_Pan_ProgressPan;
    private javax.swing.JPanel grp_Pan_MainPan;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel grp_Pan_SignaletiquePan;
    private javax.swing.JPanel grp_Pan_StatusPan;
    // End of variables declaration//GEN-END:variables
}
