/*

 * ODPanel.java

 *

 * Created on 14 octobre 2003, 16:42

 */


package srcastra.astra.gui.modules.compta.od;

import javax.swing.table.*;

import srcastra.astra.gui.modules.*;

import srcastra.astra.sys.classetransfert.*;

import srcastra.astra.gui.sys.tableModel.dossierTableModel.*;

import srcastra.astra.gui.components.actions.actionToolBar.*;

/**
 * @author Thomas
 */

public class ODPanel extends javax.swing.JPanel implements srcastra.astra.gui.components.actions.actionToolBar.ToolBarComposer {


    /**
     * Creates new form ODPanel
     */

    MainScreenModule parent;

    Loginusers_T currentUser;

    ODModel model;

    public ODPanel(MainScreenModule parent, int type) {

        this.parent = parent;

        currentUser = parent.getCurrentUser();

        initComponents();

        if (type == 0) {

            jLabel5.setVisible(false);

            grp_tfield_soldeini.setVisible(false);

        }

        initTable();


    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * initialize the form.
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * always regenerated by the Form Editor.
     */

    private void initTable() {

        //  grp_Table_Achat.setFocusable(false);

        grp_Table_odbk.setSelectionBackground(new java.awt.Color(204, 204, 255));

        this.model = new ODModel(parent, parent.getCurrentUser());

        grp_Table_odbk.setAutoCreateColumnsFromModel(false);

        grp_Table_odbk.getTableHeader().setReorderingAllowed(false);

        grp_Table_odbk.setModel(this.model);

        grp_Table_odbk.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        for (int k = 0; k < model.m_columns.length; k++) {

            /* DefaultTableCellRenderer renderer=new ColoredTableCellRenderer();

       renderer.setHorizontalAlignment(model.m_columns[k].c_alignement);

       TableColumn column=null;

       if(k==0){

         TableCellEditor editor=new ListeCellEditor(instanciateListeCompte(),k,false,model,editable.getMouse(),editable);

         editor.addCellEditorListener(editable);

         column=new TableColumn(k,model.m_columns[k].c_width,renderer,editor);

       }

       else if(k==1){

           TableCellEditor editor=new ListeCellEditor(instanciateListeTva(),k,true,model,editable.getMouse(),editable);

           editor.addCellEditorListener(editable);

           column=new TableColumn(k,model.m_columns[k].c_width,renderer,editor);

       }

       else if(k==2){

         TableCellEditor editor=new TextFieldEditor(instanciateTextField(2),k,true,model,editable.getMouse(),editable);

         editor.addCellEditorListener(editable);

         column=new TableColumn(k,model.m_columns[k].c_width,renderer,editor);    }

        else if(k==3){

         TableCellEditor editor=new TextFieldEditor(instanciateTextField(3),k,false,model,editable.getMouse(),editable);

         editor.addCellEditorListener(editable);

         column=new TableColumn(k,model.m_columns[k].c_width,renderer,editor);    }

        else if(k==4){

         TableCellEditor editor=new TextFieldEditor(instanciateTextField(1),k,false,model,editable.getMouse(),editable);

         editor.addCellEditorListener(editable);

         column=new TableColumn(k,model.m_columns[k].c_width,renderer,editor);    }

        else if(k==5){

         TableCellEditor editor=new TextFieldEditor(instanciateTextField(1),k,false,model,editable.getMouse(),editable);

         editor.addCellEditorListener(editable);

         column=new TableColumn(k,model.m_columns[k].c_width,renderer,editor);    }

       column.setHeaderValue(model.m_columns[k].c_title);

       grp_Table_Achat.addColumn(column);     */

            DefaultTableCellRenderer renderer = new ColoredTableCellRenderer();

            renderer.setHorizontalAlignment(model.m_columns[k].c_alignement);

            TableColumn column = null;

            column = new TableColumn(k, model.m_columns[k].c_width, renderer, null);

            column.setHeaderValue(model.m_columns[k].c_title);

            grp_Table_odbk.addColumn(column);

        }

        JTableHeader header = grp_Table_odbk.getTableHeader();

        header.setUpdateTableInRealTime(false);

        header.setResizingAllowed(false);

        if (grp_Table_odbk.getRowCount() != 0) ;

        grp_Table_odbk.changeSelection(0, 0, false, false);

    }

    private void initComponents() {//GEN-BEGIN:initComponents

        java.awt.GridBagConstraints gridBagConstraints;


        jPanel1 = new javax.swing.JPanel();

        jScrollPane1 = new javax.swing.JScrollPane();

        grp_Table_odbk = new srcastra.astra.gui.components.frame.MY_Table();

        jPanel2 = new javax.swing.JPanel();

        jPanel4 = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();

        jLabel2 = new javax.swing.JLabel();

        jLabel3 = new javax.swing.JLabel();

        grp_liste_journal = new srcastra.astra.gui.components.combobox.liste.Liste();

        grp_liste_periode = new srcastra.astra.gui.components.combobox.liste.Liste();

        grp_combo_piece = new srcastra.astra.gui.components.checkbox.ACheckBox();

        jLabel4 = new javax.swing.JLabel();

        grp_tfield_document = new srcastra.astra.gui.components.textFields.ATextField();

        jLabel5 = new javax.swing.JLabel();

        grp_tfield_soldeini = new srcastra.astra.gui.components.textFields.ATextField();

        jPanel3 = new javax.swing.JPanel();


        setLayout(new java.awt.BorderLayout());


        jPanel1.setLayout(new java.awt.BorderLayout());


        grp_Table_odbk.setModel(new DefaultTableModel());

        jScrollPane1.setViewportView(grp_Table_odbk);


        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);


        add(jPanel1, java.awt.BorderLayout.CENTER);


        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));


        jPanel2.setPreferredSize(new java.awt.Dimension(10, 25));

        jPanel4.setLayout(new java.awt.GridBagLayout());


        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10));

        jLabel1.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/compta", currentUser.getLangage()).getString("A_journ"));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);

        jPanel4.add(jLabel1, gridBagConstraints);


        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10));

        jLabel2.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/compta", currentUser.getLangage()).getString("A_per"));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 2;

        gridBagConstraints.gridy = 0;

        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);

        jPanel4.add(jLabel2, gridBagConstraints);


        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10));

        jLabel3.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/compta", currentUser.getLangage()).getString("oddoc"));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 4;

        gridBagConstraints.gridy = 0;

        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);

        jPanel4.add(jLabel3, gridBagConstraints);


        grp_liste_journal.setEnabled(false);

        grp_liste_journal.setPreferredSize(new java.awt.Dimension(100, 18));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 1;

        gridBagConstraints.gridy = 0;

        jPanel4.add(grp_liste_journal, gridBagConstraints);


        grp_liste_periode.setEnabled(false);

        grp_liste_periode.setPreferredSize(new java.awt.Dimension(100, 18));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 3;

        gridBagConstraints.gridy = 0;

        jPanel4.add(grp_liste_periode, gridBagConstraints);


        grp_combo_piece.setEnabled(false);

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 7;

        gridBagConstraints.gridy = 0;

        jPanel4.add(grp_combo_piece, gridBagConstraints);


        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10));

        jLabel4.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/compta", currentUser.getLangage()).getString("odpiece"));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 6;

        gridBagConstraints.gridy = 0;

        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);

        jPanel4.add(jLabel4, gridBagConstraints);


        grp_tfield_document.setEnabled(false);

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 5;

        gridBagConstraints.gridy = 0;

        jPanel4.add(grp_tfield_document, gridBagConstraints);


        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));

        jLabel5.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/compta", currentUser.getLangage()).getString("bksoldeinit"));

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 8;

        gridBagConstraints.gridy = 0;

        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);

        jPanel4.add(jLabel5, gridBagConstraints);


        grp_tfield_soldeini.setEnabled(false);

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 9;

        gridBagConstraints.gridy = 0;

        jPanel4.add(grp_tfield_soldeini, gridBagConstraints);


        jPanel2.add(jPanel4);


        add(jPanel2, java.awt.BorderLayout.NORTH);


        add(jPanel3, java.awt.BorderLayout.SOUTH);


    }//GEN-END:initComponents


    public void doAccept() {

    }


    public void doCancel() {

    }


    public void doClose() {

        parent.closeModule();

    }


    public void doCreate() {

    }


    public void doDelete() {

    }


    public void doF10() {

    }


    public void doF7() {

    }


    public void doHelp() {

    }


    public void doModify() {

    }


    public void doNext() {

    }


    public void doPrevious() {

    }


    public void doPrint() {

    }


    public void doSwitch() {

    }


    public int[] getDefaultActionToolBarMask() {

        return new int[]{ActionToolBar.DO_CLOSE};

    }


    public java.awt.Component m_getGeneriqueTable() {

        return null;

    }


    public void setThisAsToolBarComponent() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private srcastra.astra.gui.components.frame.MY_Table grp_Table_odbk;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_combo_piece;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_liste_journal;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_liste_periode;

    private srcastra.astra.gui.components.textFields.ATextField grp_tfield_document;

    private srcastra.astra.gui.components.textFields.ATextField grp_tfield_soldeini;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JScrollPane jScrollPane1;

    // End of variables declaration//GEN-END:variables


}

