/*

 * AvionExchange.java

 *

 * Created on 28 octobre 2003, 14:42

 */


package srcastra.astra.gui.modules.dossier.productSpecification.avioncancel;

import srcastra.astra.sys.classetransfert.*;

/**
 * @author Thomas
 */

public class AvionExchange extends javax.swing.JPanel {


    /**
     * Creates new form AvionExchange
     */

    Loginusers_T currentUser;

    public AvionExchange(Loginusers_T currentUser) {

        this.currentUser = currentUser;

        setBounds(0, 0, 500, 250);

        initComponents();

    }

    /**
     * This method is called from within the constructor to
     * <p/>
     * initialize the form.
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * always regenerated by the Form Editor.
     */

    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();

        jTextPane1 = new javax.swing.JTextPane();


        setLayout(new java.awt.BorderLayout());


        setBorder(new javax.swing.border.TitledBorder(null, java.util.ResourceBundle.getBundle("srcastra/astra/locale/ModuleDossier/DossierProduitPane", currentUser.getLangage()).getString("caav_exchange"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10)));

        jScrollPane1.setViewportView(jTextPane1);


        add(jScrollPane1, java.awt.BorderLayout.CENTER);


    }//GEN-END:initComponents


    /**
     * Getter for property jTextPane1.
     *
     * @return Value of property jTextPane1.
     */

    public javax.swing.JTextPane getJTextPane1() {

        return jTextPane1;

    }


    /**
     * Setter for property jTextPane1.
     *
     * @param jTextPane1 New value of property jTextPane1.
     */

    public void setJTextPane1(javax.swing.JTextPane jTextPane1) {

        this.jTextPane1 = jTextPane1;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTextPane jTextPane1;

    // End of variables declaration//GEN-END:variables


}

