/*
 * JcheckSum.java
 *
 * Created on 12 février 2003, 14:52
 */

package srcastra.astra.sys.compta;

/**
 *
 * @author  thomas
 */
public class JcheckSum extends javax.swing.JDialog {
    srcastra.astra.sys.compta.CheckSum_T check;
    
    /** Creates new form JcheckSum */
    public JcheckSum(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setTitle("R\u00e9sum\u00e9 des op\u00e9rations Comptable");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(600, 300));
        setLocation((screenSize.width-600)/2,(screenSize.height-300)/2);
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JcheckSum(new javax.swing.JFrame(), true).show();
    }
    
    /** Getter for property check.
     * @return Value of property check.
     */
    public srcastra.astra.sys.compta.CheckSum_T getCheck() {
        return check;
    }    
    
    /** Setter for property check.
     * @param check New value of property check.
     */
    public void setCheck(srcastra.astra.sys.compta.CheckSum_T check) {
        this.check = check;
        getContentPane().add(new PCheckSumCompta(check));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
