/*
 * LangueSystem.java
 *
 * Created on 6 mai 2002, 15:51
 */

package srcastra.astra.gui.modules.parametrage;

/**
 *
 * @author  Administrateur
 */
public class LangueSystem extends javax.swing.JPanel {

    /** Creates new form LangueSystem */
    public LangueSystem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
