/*

 * TestFont.java

 *

 * Created on 3 juin 2003, 9:59

 */


package srcastra.astra.gui.modules.debug;

import java.awt.*;

/**
 * @author Thomas
 */

public class TestFont extends javax.swing.JDialog {


    /**
     * Creates new form TestFont
     */

    public TestFont(java.awt.Frame parent, boolean modal) {

        super(parent, modal);

        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();

        String fontNames[] = ge.getAvailableFontFamilyNames();

        // Iterate the font family names

        jTextPane1.setText("Test des différentes font\n");

        for (int i = 0; i < fontNames.length; i++) {

            System.out.println("font " + fontNames[i]);

            jTextPane1.setText(jTextPane1.getText() + "font " + i + " " + fontNames[i] + "\n");

        }

    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * initialize the form.
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * always regenerated by the Form Editor.
     */

    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();

        jTextPane1 = new javax.swing.JTextPane();


        addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent evt) {

                closeDialog(evt);

            }

        });


        jTextPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        jScrollPane1.setViewportView(jTextPane1);


        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);


        pack();

    }//GEN-END:initComponents


    /**
     * Closes the dialog
     */

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

        setVisible(false);

        dispose();

    }//GEN-LAST:event_closeDialog


    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {

        new TestFont(new javax.swing.JFrame(), true).show();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTextPane jTextPane1;

    // End of variables declaration//GEN-END:variables


}

