/*

 * AchatMainPanel.java

 *

 * Created on 30 juillet 2003, 12:14

 */


package srcastra.astra.gui.modules.compta.achat;


/**
 * @author Thomas
 */

public class AchatMainPanel extends javax.swing.JPanel {


    /**
     * Creates new form AchatMainPanel
     */

    public AchatMainPanel() {

        initComponents();

    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * initialize the form.
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * always regenerated by the Form Editor.
     */

    private void initComponents() {//GEN-BEGIN:initComponents

        java.awt.GridBagConstraints gridBagConstraints;


    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com14;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant6;

    private javax.swing.JLabel jLabel512;

    private javax.swing.JPanel jPanel54;

    private javax.swing.JPanel jPanel37;

    private javax.swing.JPanel AchatPanel7;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode4;

    private javax.swing.JPanel jPanel26;

    private javax.swing.JLabel jLabel210;

    private javax.swing.JLabel jLabel610;

    private javax.swing.JPanel jPanel61;

    private javax.swing.JLabel jLabel615;

    private javax.swing.JLabel jLabel412;

    private javax.swing.JPanel jPanel39;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode6;

    private javax.swing.JLabel jLabel23;

    private javax.swing.JLabel jLabel96;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JPanel jPanel511;

    private javax.swing.JPanel AchatPanel3;

    private javax.swing.JLabel jLabel613;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant4;

    private javax.swing.JPanel jPanel73;

    private javax.swing.JPanel jPanel613;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise9;

    private javax.swing.JLabel jLabel61;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers9;

    private javax.swing.JLabel jLabel611;

    private javax.swing.JPanel jPanel714;

    private javax.swing.JPanel AchatPanel1;

    private javax.swing.JPanel jPanel615;

    private javax.swing.JLabel jLabel63;

    private javax.swing.JPanel jPanel28;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant8;

    private srcastra.astra.gui.components.date.thedate.ADate aDate16;

    private javax.swing.JLabel jLabel34;

    private javax.swing.JLabel jLabel88;

    private javax.swing.JPanel jPanel56;

    private javax.swing.JLabel jLabel710;

    private javax.swing.JLabel jLabel410;

    private javax.swing.JLabel jLabel21;

    private javax.swing.JLabel jLabel71;

    private srcastra.astra.gui.components.date.thedate.ADate aDate14;

    private javax.swing.JPanel jPanel912;

    private javax.swing.JPanel jPanel211;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com8;

    private javax.swing.JLabel jLabel510;

    private srcastra.astra.gui.components.date.thedate.ADate aDate112;

    private javax.swing.JLabel jLabel32;

    private javax.swing.JPanel jPanel710;

    private javax.swing.JLabel jLabel57;

    private javax.swing.JPanel jPanel24;

    private javax.swing.JPanel jPanel52;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece15;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur7;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal2;

    private srcastra.astra.gui.components.date.thedate.ADate aDate12;

    private javax.swing.JPanel jPanel22;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel25;

    private javax.swing.JLabel jLabel913;

    private javax.swing.JLabel jLabel36;

    private javax.swing.JPanel jPanel89;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece11;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant12;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers11;

    private javax.swing.JLabel jLabel27;

    private srcastra.astra.gui.components.date.thedate.ADate aDate110;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers;

    private javax.swing.JPanel jPanel16;

    private javax.swing.JPanel jPanel42;

    private javax.swing.JPanel jPanel71;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal11;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode14;

    private javax.swing.JLabel jLabel915;

    private javax.swing.JLabel jLabel14;

    private javax.swing.JPanel jPanel311;

    private javax.swing.JPanel jPanel611;

    private javax.swing.JLabel jLabel114;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com10;

    private srcastra.astra.gui.components.date.thedate.ADate aDate114;

    private javax.swing.JLabel jLabel414;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece9;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur1;

    private javax.swing.JLabel jLabel38;

    private javax.swing.JPanel jPanel96;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode8;

    private javax.swing.JLabel jLabel16;

    private javax.swing.JPanel jPanel313;

    private javax.swing.JLabel jLabel18;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece13;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur;

    private javax.swing.JPanel jPanel6;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur11;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com12;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com6;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JPanel AchatPanel5;

    private javax.swing.JLabel jLabel12;

    private javax.swing.JLabel jLabel55;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece6;

    private javax.swing.JPanel jPanel47;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode2;

    private javax.swing.JPanel jPanel910;

    private javax.swing.JPanel jPanel69;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur15;

    private javax.swing.JLabel jLabel73;

    private javax.swing.JLabel jLabel51;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel63;

    private javax.swing.JPanel jPanel87;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal13;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant14;

    private javax.swing.JLabel jLabel314;

    private javax.swing.JLabel jLabel75;

    private javax.swing.JLabel jLabel59;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal15;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode12;

    private javax.swing.JLabel jLabel94;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers1;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais8;

    private javax.swing.JPanel jPanel75;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode11;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers3;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais1;

    private javax.swing.JLabel jLabel312;

    private javax.swing.JPanel jPanel29;

    private javax.swing.JLabel jLabel92;

    private javax.swing.JPanel jPanel915;

    private javax.swing.JLabel jLabel86;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais3;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers5;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise2;

    private javax.swing.JLabel jLabel310;

    private javax.swing.JLabel jLabel79;

    private javax.swing.JLabel jLabel814;

    private javax.swing.JPanel jPanel815;

    private javax.swing.JLabel jLabel84;

    private javax.swing.JLabel jLabel212;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant10;

    private javax.swing.JLabel jLabel82;

    private javax.swing.JLabel jLabel111;

    private javax.swing.JLabel jLabel214;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais7;

    private javax.swing.JPanel jPanel46;

    private javax.swing.JLabel jLabel47;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise15;

    private javax.swing.JPanel jPanel77;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais9;

    private javax.swing.JPanel jPanel214;

    private javax.swing.JPanel jPanel44;

    private javax.swing.JLabel jLabel811;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece5;

    private javax.swing.JPanel jPanel92;

    private javax.swing.JPanel jPanel410;

    private javax.swing.JLabel jLabel98;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise4;

    private javax.swing.JPanel jPanel79;

    private javax.swing.JPanel jPanel4;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise11;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers7;

    private javax.swing.JPanel jPanel68;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais5;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JPanel jPanel913;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur12;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com4;

    private srcastra.astra.gui.components.date.thedate.ADate aDate18;

    private javax.swing.JPanel jPanel66;

    private javax.swing.JLabel jLabel19;

    private javax.swing.JPanel jPanel8;

    private javax.swing.JLabel jLabel715;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece2;

    private javax.swing.JLabel jLabel28;

    private javax.swing.JPanel jPanel94;

    private javax.swing.JPanel jPanel32;

    private javax.swing.JPanel jPanel59;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece14;

    private javax.swing.JPanel jPanel85;

    private javax.swing.JPanel jPanel53;

    private srcastra.astra.gui.components.date.thedate.ADate aDate111;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal5;

    private javax.swing.JPanel jPanel98;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant3;

    private javax.swing.JPanel jPanel12;

    private javax.swing.JPanel jPanel81;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur5;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais15;

    private javax.swing.JLabel jLabel911;

    private javax.swing.JLabel jLabel713;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant1;

    private javax.swing.JLabel jLabel41;

    private javax.swing.JPanel jPanel83;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais13;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JPanel jPanel14;

    private javax.swing.JPanel jPanel51;

    private javax.swing.JLabel jLabel77;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com1;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur9;

    private javax.swing.JPanel jPanel812;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais11;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal9;

    private javax.swing.JLabel jLabel43;

    private javax.swing.JLabel jLabel513;

    private javax.swing.JPanel jPanel513;

    private srcastra.astra.gui.components.date.thedate.ADate aDate1;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais;

    private javax.swing.JLabel jLabel68;

    private javax.swing.JPanel jPanel412;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise13;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal7;

    private javax.swing.JPanel jPanel38;

    private javax.swing.JLabel jLabel45;

    private javax.swing.JPanel jPanel212;

    private javax.swing.JLabel jLabel66;

    private javax.swing.JPanel jPanel36;

    private javax.swing.JPanel jPanel414;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers14;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise8;

    private javax.swing.JLabel jLabel711;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur3;

    private javax.swing.JPanel jPanel712;

    private javax.swing.JPanel jPanel515;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise6;

    private javax.swing.JLabel jLabel49;

    private javax.swing.JLabel jLabel93;

    private javax.swing.JPanel jPanel711;

    private javax.swing.JLabel jLabel614;

    private javax.swing.JLabel jLabel411;

    private javax.swing.JLabel jLabel511;

    private javax.swing.JPanel jPanel614;

    private javax.swing.JLabel jLabel91;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com2;

    private javax.swing.JLabel jLabel35;

    private javax.swing.JLabel jLabel62;

    private javax.swing.JPanel jPanel310;

    private javax.swing.JPanel AchatPanel2;

    private srcastra.astra.gui.components.date.thedate.ADate aDate13;

    private javax.swing.JPanel jPanel612;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com15;

    private javax.swing.JPanel jPanel27;

    private javax.swing.JLabel jLabel515;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal10;

    private javax.swing.JPanel jPanel55;

    private javax.swing.JLabel jLabel37;

    private javax.swing.JPanel jPanel57;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece10;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant5;

    private javax.swing.JLabel jLabel58;

    private javax.swing.JLabel jLabel72;

    private javax.swing.JPanel jPanel514;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers8;

    private javax.swing.JPanel jPanel34;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece;

    private javax.swing.JLabel jLabel612;

    private javax.swing.JPanel jPanel72;

    private javax.swing.JLabel jLabel56;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant7;

    private srcastra.astra.gui.components.date.thedate.ADate aDate15;

    private javax.swing.JLabel jLabel8;

    private srcastra.astra.gui.components.date.thedate.ADate aDate113;

    private javax.swing.JLabel jLabel26;

    private javax.swing.JLabel jLabel87;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers15;

    private javax.swing.JPanel jPanel82;

    private javax.swing.JPanel jPanel25;

    private javax.swing.JLabel jLabel24;

    private javax.swing.JLabel jLabel89;

    private javax.swing.JPanel jPanel510;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur8;

    private javax.swing.JPanel jPanel210;

    private javax.swing.JPanel jPanel512;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers12;

    private javax.swing.JLabel jLabel97;

    private javax.swing.JLabel jLabel11;

    private javax.swing.JPanel jPanel17;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers10;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant11;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com7;

    private javax.swing.JLabel jLabel211;

    private javax.swing.JLabel jLabel22;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece12;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com9;

    private javax.swing.JPanel jPanel23;

    private javax.swing.JPanel jPanel48;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal3;

    private javax.swing.JPanel AchatPanel;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant15;

    private javax.swing.JPanel jPanel312;

    private javax.swing.JLabel jLabel52;

    private javax.swing.JLabel jLabel813;

    private javax.swing.JPanel jPanel88;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal12;

    private javax.swing.JLabel jLabel313;

    private javax.swing.JPanel jPanel95;

    private srcastra.astra.gui.components.date.thedate.ADate aDate19;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur2;

    private javax.swing.JLabel jLabel113;

    private javax.swing.JLabel jLabel415;

    private javax.swing.JPanel jPanel74;

    private javax.swing.JLabel jLabel17;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com13;

    private javax.swing.JPanel jPanel610;

    private javax.swing.JLabel jLabel315;

    private javax.swing.JPanel jPanel1;

    private srcastra.astra.gui.components.date.thedate.ADate aDate115;

    private javax.swing.JLabel jLabel39;

    private javax.swing.JPanel jPanel715;

    private javax.swing.JLabel jLabel64;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal1;

    private javax.swing.JPanel jPanel64;

    private javax.swing.JLabel jLabel33;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal14;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel13;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode7;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode13;

    private javax.swing.JLabel jLabel54;

    private javax.swing.JLabel jLabel311;

    private javax.swing.JPanel jPanel814;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece7;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur10;

    private javax.swing.JPanel jPanel62;

    private javax.swing.JPanel jPanel810;

    private javax.swing.JLabel jLabel95;

    private javax.swing.JLabel jLabel74;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece4;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode15;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode5;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode1;

    private javax.swing.JPanel AchatPanel4;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais2;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers2;

    private javax.swing.JPanel jPanel97;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode3;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com11;

    private javax.swing.JLabel jLabel413;

    private javax.swing.JPanel jPanel314;

    private javax.swing.JLabel jLabel815;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant13;

    private javax.swing.JLabel jLabel31;

    private javax.swing.JPanel AchatPanel6;

    private javax.swing.JLabel jLabel15;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode9;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_periode10;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais4;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise1;

    private javax.swing.JLabel jLabel46;

    private javax.swing.JPanel jPanel911;

    private javax.swing.JPanel jPanel76;

    private javax.swing.JLabel jLabel81;

    private javax.swing.JLabel jLabel67;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers4;

    private javax.swing.JPanel jPanel43;

    private javax.swing.JLabel jLabel810;

    private javax.swing.JLabel jLabel44;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur14;

    private javax.swing.JLabel jLabel213;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JPanel jPanel215;

    private javax.swing.JPanel jPanel315;

    private javax.swing.JLabel jLabel78;

    private javax.swing.JLabel jLabel812;

    private javax.swing.JLabel jLabel85;

    private javax.swing.JPanel jPanel415;

    private javax.swing.JLabel jLabel48;

    private javax.swing.JPanel jPanel31;

    private javax.swing.JLabel jLabel914;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel115;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers6;

    private javax.swing.JPanel jPanel93;

    private javax.swing.JPanel jPanel914;

    private javax.swing.JPanel jPanel3;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise14;

    private javax.swing.JPanel jPanel49;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com5;

    private javax.swing.JPanel jPanel5;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece1;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise3;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur13;

    private javax.swing.JPanel jPanel65;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece8;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_com3;

    private javax.swing.JLabel jLabel69;

    private javax.swing.JPanel jPanel21;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant9;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_numpiece3;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais6;

    private javax.swing.JPanel jPanel67;

    private javax.swing.JLabel jLabel53;

    private javax.swing.JPanel jPanel15;

    private javax.swing.JLabel jLabel99;

    private javax.swing.JPanel jPanel9;

    private javax.swing.JPanel jPanel45;

    private srcastra.astra.gui.components.date.thedate.ADate aDate17;

    private javax.swing.JPanel jPanel13;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant2;

    private javax.swing.JPanel jPanel33;

    private javax.swing.JPanel jPanel411;

    private javax.swing.JPanel jPanel41;

    private javax.swing.JLabel jLabel714;

    private srcastra.astra.gui.components.textFields.ATextField grp_TFields_montant;

    private javax.swing.JPanel jPanel91;

    private javax.swing.JPanel jPanel58;

    private javax.swing.JPanel jPanel35;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal4;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_tiers13;

    private srcastra.astra.gui.components.date.thedate.ADate aDate11;

    private javax.swing.JLabel jLabel29;

    private javax.swing.JLabel jLabel42;

    private javax.swing.JLabel jLabel912;

    private javax.swing.JPanel jPanel84;

    private javax.swing.JPanel jPanel213;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur6;

    private javax.swing.JLabel jLabel5;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise10;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal6;

    private javax.swing.JLabel jLabel76;

    private javax.swing.JPanel jPanel811;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal;

    private javax.swing.JLabel jLabel65;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais10;

    private javax.swing.JPanel jPanel78;

    private javax.swing.JLabel jLabel910;

    private javax.swing.JPanel jPanel413;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_journal8;

    private javax.swing.JLabel jLabel712;

    private javax.swing.JPanel jPanel713;

    private javax.swing.JPanel jPanel11;

    private javax.swing.JLabel jLabel215;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais12;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise12;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise5;

    private javax.swing.JPanel jPanel86;

    private javax.swing.JLabel jLabel112;

    private javax.swing.JLabel jLabel83;

    private srcastra.astra.gui.components.textFields.ATextField grp_TField_montanteur4;

    private srcastra.astra.gui.components.checkbox.ACheckBox grp_Cbox_Frais14;

    private javax.swing.JPanel jPanel99;

    private srcastra.astra.gui.components.combobox.liste.Liste grp_Liste_devise7;

    private javax.swing.JLabel jLabel514;

    private javax.swing.JLabel jLabel110;

    private javax.swing.JPanel jPanel813;

    // End of variables declaration//GEN-END:variables


}

