/*

 * FacturePrompt.java

 *

 * Created on 4 juin 2003, 9:04

 */


package srcastra.astra.gui.modules.dossier;

import srcastra.astra.gui.modules.mainScreenModule.*;

import srcastra.astra.sys.rmi.*;

import srcastra.astra.gui.sys.*;

import srcastra.astra.sys.classetransfert.utils.*;


/**
 * @author Thomas
 */

public class FacturePrompt extends javax.swing.JDialog {


    /**
     * Creates new form FacturePrompt
     */

    DossierMainScreenModule parent;

    public FacturePrompt(java.awt.Frame parentf, boolean modal, DossierMainScreenModule parent) {

        super(parentf, modal);

        this.parent = parent;

        initComponents();

    }


    /**
     * This method is called from within the constructor to
     * <p/>
     * initialize the form.
     * <p/>
     * WARNING: Do NOT modify this code. The content of this method is
     * <p/>
     * always regenerated by the Form Editor.
     */

    private void initComponents() {//GEN-BEGIN:initComponents

        java.awt.GridBagConstraints gridBagConstraints;


        buttonGroup1 = new javax.swing.ButtonGroup();

        jPanel1 = new javax.swing.JPanel();

        jPanel2 = new javax.swing.JPanel();

        grp_radio_factdetail = new javax.swing.JRadioButton();

        jButton1 = new javax.swing.JButton();

        grp_radio_factnodetail = new javax.swing.JRadioButton();


        addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent evt) {

                closeDialog(evt);

            }

        });


        jPanel2.setLayout(new java.awt.GridBagLayout());


        grp_radio_factdetail.setFont(new java.awt.Font("Tahoma", 1, 10));

        grp_radio_factdetail.setSelected(true);

        grp_radio_factdetail.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/generale", parent.getCurrentUser().getLangage()).getString("fact_detaille"));

        buttonGroup1.add(grp_radio_factdetail);

        jPanel2.add(grp_radio_factdetail, new java.awt.GridBagConstraints());


        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10));

        jButton1.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/generale", parent.getCurrentUser().getLangage()).getString("config_bur_acc"));

        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton1ActionPerformed(evt);

            }

        });


        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 1;

        gridBagConstraints.gridy = 2;

        jPanel2.add(jButton1, gridBagConstraints);


        grp_radio_factnodetail.setFont(new java.awt.Font("Tahoma", 1, 10));

        grp_radio_factnodetail.setText(java.util.ResourceBundle.getBundle("srcastra/astra/locale/generale", parent.getCurrentUser().getLangage()).getString("fact_ndetail"));

        buttonGroup1.add(grp_radio_factnodetail);

        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 2;

        gridBagConstraints.gridy = 0;

        jPanel2.add(grp_radio_factnodetail, gridBagConstraints);


        jPanel1.add(jPanel2);


        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);


        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();

        setBounds((screenSize.width - 400) / 2, (screenSize.height - 85) / 2, 400, 85);

    }//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();

        int fact = 1;

        if (grp_radio_factnodetail.isSelected())

            fact = 2;

        try {

            if (parent.getDossier().getDr_facture() == 0) {

                parent.getDossier().setDr_date_facturation(CalculDate.getTodayDate());

                // String numfact=((Report1)this).getServeur().renvParamCompta(((Report1)this).getUser().getUrcleunik()).checkNumeroFacture(((Report1)this).getUser().getUrcleunik());

                //      parent.getDossier().setNumfact(parent.getServeur().renvParamCompta(parent.getCurrentUser().getUrcleunik()).checkNumero(parent.getCurrentUser().getUrcleunik(),ParamComptableInterface.JOURNAL_VENTE));

                String numfact = parent.getServeur().renvDossierRmiObject(parent.getCurrentUser().getUrcleunik()).setDossierFacture(parent.getCurrentUser().getUrcleunik(), parent.getDossier().getDrcleunik(), Long.parseLong(parent.getDossier().getNumfact()), parent.getDossier().getDrtotalprix());

                parent.getDossier().setNumfact(numfact);

                parent.getDossier().setDr_facture(1);

                //  parent.getServeur().renvParamCompta(parent.getCurrentUser().getUrcleunik()).commitNumpiece(parent.getCurrentUser().getUrcleunik());

            }

            new srcastra.astra.gui.modules.printing.PrintingPreview2(parent.getSuperOwner(), parent.getServeurDossier(), parent.getDossier(), parent.getCurrentUser(), parent.getMainframe().getMediator(), parent.getServeur(), fact, true);        // Add your handling code here:

        } catch (srcastra.astra.sys.rmi.Exception.ServeurSqlFailure se) {

            ErreurScreenLibrary.displayErreur(this, ErreurScreenLibrary.SERVEUR_SQL_FAILURE, srcastra.astra.Astra.DEBUG, se);

        }

        catch (java.rmi.RemoteException re) {

            ErreurScreenLibrary.displayErreur(this, ErreurScreenLibrary.REMOTE_EXCEPTION, srcastra.astra.Astra.DEBUG, re);

        }

    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * Closes the dialog
     */

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

        setVisible(false);

        dispose();

    }//GEN-LAST:event_closeDialog


    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {

        //   new FacturePrompt(new javax.swing.JFrame(), true).show();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.ButtonGroup buttonGroup1;

    private javax.swing.JRadioButton grp_radio_factdetail;

    private javax.swing.JRadioButton grp_radio_factnodetail;

    private javax.swing.JButton jButton1;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    // End of variables declaration//GEN-END:variables


}

