"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\astra-client.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\AbsoluteLayout-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\FORMS_10-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\ITEXT-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\jdom-1.1.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\jsch-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\LOOKS_11-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\mysql-connector-java-5.1.32.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\servlet-api-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\XBASEJ-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\SMTP-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\POP3-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\MAILAPI-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\IMAP-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\ACTIVATI-0.0.jar astraclient
"C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner" -keystore astra -storepass vidaloca C:\Users\B2NEXT\projects\astraclient\classes\artifacts\astra_client_jar\JHALL-0.0.jar astraclient
